import type { NursingSchoolOption } from './nursing-schools'

// Generated by `npm run build:nursing-directory`.
// Keep this checked in so the profile picker can work offline after import.
export const generatedNursingSchoolOptions = [] satisfies NursingSchoolOption[]
